### PR TITLE
Integrate changes made on 2019-07-23

### PR DESCRIPTION
**Pull request by vincent-zurczak**
With simplifications on the structure and layout.  
You will add the video once it is ready. The welcome page will be blank, that may accelerate the creation of the video.

### CODE REVIEW

**Comment by christophechevalier** [comment]
@vincent-zurczak It's ok for me but the video must be entirely reworked because it does not correspond to what Bertrand wants.  

Should we suggest other things?  
What must be changed?  
What does he really want on the animation of the video?  
Did he talk about it with Sébastien so that he reworked what he had done?

**Comment by vincent-zurczak** [comment]
Hi @christophechevalier. :)
I know about the video that must be reworked, but it has been almost a year. And Petals is still using its old web site. The home page is supposed to be the video. Maybe having a blank page will accelerate the creation of the video. :smiling_imp:

**Comment by vincent-zurczak** [comment]
@christophechevalier I have updated my branch with the most recent animation. I also added the few white papers I could find last summer.

**Comment by cdeneux** [comment]
IMO, we should publish this new version of web site. When a video compliant with Bertrand's vision will be available we will update it with.

**Comment by christophechevalier** [comment]
> IMO, we should publish this new version of web site. When a video compliant with Bertrand's vision will be available we will update it with.

@cdeneux I shared the latest version of the video reworked by Sébastien according to Bertrand's latest feedback. If you want to see what it looks like, you can either watch it locally on the branch, or I can send it to you as I did with @vincent-zurczak.

**Review by christophechevalier — APPROVED** [review]

**Review by christophechevalier — APPROVED** [review]

**Pull request merged**
